### PR TITLE
Upgrade to log4net 2.0.3 and glimpse 1.8.6

### PR DESCRIPTION
**Pull request by willl**
I've upgraded log4net to 2.0.3 and Glimpse to 1.8.6.

I've also taken the liberty to upgrade much of the nuget packages within your demo website and a few other small updates. 

I have also updated your .gitignore file to incorporate much of the relevant bits from [github.com/github/visualstudio.gitignore](https://github.com/github/gitignore/blob/5778fded8b14e289ffb59f1fdb80960434455475/VisualStudio.gitignore). The big thing you'll notice is the removal of the nuget packages. This should mean a lighter download for anyone who needs to clone your repo in the future.

Hopefully that's alright with you. I'm happy to reverse any changes I've made or make any further changes to get this PR merged.

On reflection, I probably should not have updated your nuspec file!

### CODE REVIEW

**Comment by camitz** [comment]
Perfect!

**Comment by jchadwick** [comment]
Thanks so much for this PR!

**Comment by willl** [comment]
@jchadwick No problems, noticed it hadn't been updated in awhile so thought I'd contribute something.

**Comment by willl** [comment]
Hi @jchadwick, just wondering if you're able to update this package on [nuget](https://www.nuget.org/packages/Glimpse.Log4Net/)? It's still showing an older version.

Thank you! :)

**Pull request merged**
